# Generated by Django 5.1.6 on 2025-03-07 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Needy',
            fields=[
                ('id_needy', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.BigIntegerField()),
                ('pib_needy', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('login', models.CharField(max_length=100, unique=True)),
                ('photo', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TypeWork',
            fields=[
                ('code_type_work', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id_volunteer', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.BigIntegerField()),
                ('pib_volunteer', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('login', models.CharField(max_length=100, unique=True)),
                ('photo', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(max_length=255)),
                ('amount_of_help', models.IntegerField()),
                ('code_type_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.typework')),
            ],
        ),
    ]
