# Generated by Django 5.1.6 on 2025-03-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_needy_id_needy_alter_typework_code_type_work_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needy',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='needy_photos/'),
        ),
    ]
