# Generated by Django 5.1.6 on 2025-03-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='code_request',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='id_service',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
